# Generated by Django 5.2.11 on 2026-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price_hidden',
            field=models.BooleanField(default=False, verbose_name='Giá liên hệ'),
        ),
    ]
