# Generated by Django 5.2.13 on 2026-04-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
