# Generated by Django 5.2.13 on 2026-04-17 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage_file_chatmessage_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn chat', 'verbose_name_plural': 'Quản lý tin nhắn'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/', verbose_name='Tệp đính kèm'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Hình ảnh'), ('document', 'Tài liệu'), ('video', 'Video'), ('audio', 'Âm thanh')], max_length=20, null=True, verbose_name='Loại tệp đính kèm'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Trạng thái đã xem'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.consultationrequest', verbose_name='Yêu cầu tư vấn'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_staff_reply',
            field=models.BooleanField(default=False, verbose_name='Là phản hồi của Admin/Staff'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
    ]
