"""
Django settings for insurance_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-(0kzvcq26ea8up&2uh_0f%@e-i+^je)g3c!d#s8re!v4h-6d+g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py (Chỉ bật khi lên Production và có HTTPS)

if not DEBUG:
    SECURE_SSL_REDIRECT = True # Ép buộc dùng HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY' # Chống bị nhúng vào iframe (Clickjacking)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'corsheaders',
    'django_filters',
    # Local
    'api',
    #'chat',
]

# 2. THÊM DÒNG NÀY (Bắt buộc)
ASGI_APPLICATION = 'insurance_project.asgi.application'

# 3. Đảm bảo cấu hình Channel Layers đã có (Dùng cho Chat realtime)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Đặt đầu tiên
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'api.User' # Sử dụng model User tùy chỉnh
CORS_ALLOW_ALL_ORIGINS = True # Dev only


# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # --- THÊM PHẦN NÀY ---
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # Khách vãng lai
        'rest_framework.throttling.UserRateThrottle'  # User đã đăng nhập
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',   # Khách chỉ được gọi 100 lần/ngày
        'user': '1000/day',  # User được gọi 1000 lần/ngày
    }
}



# settings.py

# Thay vì CORS_ALLOW_ALL_ORIGINS = True (Chỉ dùng khi Dev)
# Hãy dùng:
CORS_ALLOWED_ORIGINS = [
    "https://tisbroker.com",
    "https://www.tisbroker.com",
    "http://localhost:5500", # Cho phép khi test local
    "http://localhost:8000"
]




ROOT_URLCONF = 'insurance_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insurance_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




#token

# settings.py

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),  # Token chính sống 10 phút
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Token dự phòng sống 1 ngày
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}




# backend/insurance_project/settings.py

import os

# Đường dẫn URL để truy cập ảnh (ví dụ: http://127.0.0.1:8000/media/anh.jpg)
MEDIA_URL = '/media/'

# Thư mục thực tế trên ổ cứng để lưu trữ ảnh
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')